# We have a conf directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "openFPGALoader"
BBFILE_PATTERN_openFPGALoader = "^${LAYERDIR}/"
BBFILE_PRIORITY_openFPGALoader = "10"

LAYERSERIES_COMPAT_openFPGALoader = "scarthgap"
LAYERDEPENDS_openFPGALoader = "core openembedded-layer"
